columns:
  - loan_amnt: float64
  - term: int64
  - int_rate: float64
  - installment: float64
  - annual_inc: float64
  - dti: float64
  - open_acc: float64
  - pub_rec: float64
  - revol_bal: float64
  - total_acc: float64
  - mort_acc: float64
  - loan_repaid: int64
  - A2: bool
  - A3: bool
  - A4: bool
  - A5: bool
  - B1: bool
  - B2: bool
  - B3: bool
  - B4: bool
  - B5: bool
  - C1: bool
  - C2: bool
  - C3: bool
  - C4: bool
  - C5: bool
  - D1: bool
  - D2: bool
  - D3: bool
  - D4: bool
  - D5: bool
  - E1: bool
  - E2: bool
  - E3: bool
  - E4: bool
  - E5: bool
  - F1: bool
  - F2: bool
  - F3: bool
  - F4: bool
  - F5: bool
  - G1: bool
  - G2: bool
  - G3: bool
  - G4: bool
  - G5: bool
  - verification_status_Source Verified: bool
  - verification_status_Verified: bool
  - application_type_INDIVIDUAL: bool
  - application_type_JOINT: bool
  - initial_list_status_w: bool
  - purpose_credit_card: bool
  - purpose_debt_consolidation: bool
  - purpose_educational: bool
  - purpose_home_improvement: bool
  - purpose_house: bool
  - purpose_major_purchase: bool
  - purpose_medical: bool
  - purpose_moving: bool
  - purpose_other: bool
  - purpose_renewable_energy: bool
  - purpose_small_business: bool
  - purpose_vacation: bool
  - purpose_wedding: bool
  - OTHER: bool
  - OWN: bool
  - RENT: bool
  - 05113: bool
  - 11650: bool
  - 22690: bool
  - 29597: bool
  - 30723: bool
  - 48052: bool
  - 70466: bool
  - 86630: bool
  - 93700: bool
  - earliest_cr_year: int64

numerical_columns:
  - loan_amnt
  - term
  - int_rate
  - installment
  - annual_inc
  - dti
  - open_acc
  - pub_rec
  - revol_bal
  - total_acc
  - mort_acc
  - loan_repaid
  - earliest_cr_year
